spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    druid:
      url: jdbc:mysql://localhost:3306/cnr_core?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: mrchen124578
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      #validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
# redis 配置
  redis:
    host: 192.168.182.136
    port: 6379
    timeout: 6s #连接池超时时长
    lettuce:
      pool:
        max-active: 1000 #连接池最大连接数
        max-wait: -1ms #连接池最大阻塞等待时间
        max-idle: 10 #连接池最大空闲连接
        min-idle: 5 #连接池最小空闲连接

#mybatis-plus
mybatis-plus:
  global-config:
    #刷新Mapper，只在开发环境打开
    refresh: true

elasticjob:
    zookeeper:
     server-lists: 193.112.206.32:2181
     name-space: cnr-elasticjob